version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
      - "9113:9113"
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"   # OTLP HTTP receiver
      - "55681:55681" # OTLP HTTP receiver alternative