services:
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: CrudApp@1
    networks:
      - spa
    restart: always

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--loglevel", "debug"]
    networks:
      - spa
    restart: always

  backend:
    image: backend:v1
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: crud
      DB_PASSWORD: CrudApp@1
      DB_NAME: crud_app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - spa
    restart: always

  react:
    image: react:v1
    container_name: react
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - spa
    restart: always

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - spa
  
  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    networks:
      - spa
  docker-exporter:
    image: prom/prometheus:latest
    container_name: docker-exporter
    networks:
      - spa
    ports:
      - "9323:9323"

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spa
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    restart: always
    networks:
      - spa

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    environment:
      - DATA_SOURCE_NAME=root:CrudApp@1@(mysql:3306)/information_schema
    ports:
      - "9104:9104"
    restart: always
    networks:
      - spa

networks:
  spa:
    driver: bridge